kind: Service
apiVersion: v1
metadata:
  name: django-dxample
spec:
  selector:
    app: django-dxample
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-dxample
  labels:
    app: django-dxample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-dxample
  template:
    metadata:
      labels:
        app: django-dxample
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: python
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8000
